### ISSUE TITLE
Deserialization Resources

### ISSUE THREAD

**Issue by klezVirus** [z-r0crypt/z-r0crypt.github.io#1]
Hi mate,

Really not an issue, but would you mind seeing if this is worth adding among the Deserialization Resources?

[Serialisation: The big threat](https://klezvirus.github.io/The_Big_Problem_of_Serialisation/)

This was meant to be a full deserialization course among all the major languages affected by this issue. I think it would aid people getting a better grasp of it. Of course, you're free to see and choose if it's worth it or not.

**Comment by z-r0crypt** [comment]
Hey @klezVirus ,  ya, i have seen it, definitely a great write-up.  Not sure how I missed to include this, will do it today. 

Thanks!
